# Generated by Django 6.0.7 on 2026-07-28 08:14

import django.db.models.deletion
import django_enum.fields
import shop_online.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop_online', '0002_product_sold_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='shop_online_User_role_UserRole',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': shop_online.models.UserRole['SHIPPER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivering_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=django_enum.fields.EnumCharField(choices=[('ADMIN', 'ADMIN'), ('CUSTOMER', 'CUSTOMER'), ('SHIPPER', 'SHIPPER')], default='CUSTOMER', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'CUSTOMER', 'SHIPPER'])), name='shop_online_User_role_UserRole'),
        ),
    ]
