# Generated by Django 6.0.7 on 2026-08-10 05:33

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0004_remove_address_latitude_remove_address_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='shop_online_Order_payment_method_PaymentMethod',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='shop_online_Order_payment_status_PaymentStatus',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='shop_online_Payment_method_PaymentMethod',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='shop_online_Payment_status_PaymentStatus',
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=django_enum.fields.EnumCharField(choices=[('COD', 'COD'), ('PAYOS', 'PAYOS')], default='COD', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED'), ('REFUND_PENDING', 'REFUND_PENDING')], default='PENDING', max_length=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=django_enum.fields.EnumCharField(choices=[('COD', 'COD'), ('PAYOS', 'PAYOS')], max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED'), ('REFUND_PENDING', 'REFUND_PENDING')], default='PENDING', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['COD', 'PAYOS'])), name='shop_online_Order_payment_method_PaymentMethod'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['PENDING', 'PAID', 'FAILED', 'REFUNDED', 'REFUND_PENDING'])), name='shop_online_Order_payment_status_PaymentStatus'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['COD', 'PAYOS'])), name='shop_online_Payment_method_PaymentMethod'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PAID', 'FAILED', 'REFUNDED', 'REFUND_PENDING'])), name='shop_online_Payment_status_PaymentStatus'),
        ),
    ]
