# Generated by Django 6.0.7 on 2026-08-10 06:33

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0006_remove_order_shop_online_order_payment_status_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='shop_online_Order_payment_status_PaymentStatus',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='shop_online_Payment_status_PaymentStatus',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED'), ('REFUND_PENDING', 'REFUND_PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED'), ('REFUND_PENDING', 'REFUND_PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'REFUND_PENDING', 'FAILED'])), name='shop_online_Order_payment_status_PaymentStatus'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'REFUND_PENDING', 'FAILED'])), name='shop_online_Payment_status_PaymentStatus'),
        ),
    ]
