# Generated by Django 6.0.7 on 2026-08-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0007_remove_order_shop_online_order_payment_status_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='shop_online_Order_payment_status_PaymentStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
