# Generated by Django 6.0.7 on 2026-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0008_remove_order_shop_online_order_payment_status_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(default='PHAM HOANG PHU QUY', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(default='0325391105', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_bin',
            field=models.CharField(default='970422', max_length=20),
        ),
    ]
