# Generated by Django 6.0.7 on 2026-08-23 04:49

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0009_user_bank_account_name_user_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', django_enum.fields.EnumCharField(choices=[('OFFICE', 'OFFICE'), ('PARTY', 'PARTY'), ('CASUAL', 'CASUAL'), ('SPORT', 'SPORT'), ('DATE', 'DATE'), ('WEDDING', 'WEDDING'), ('TRAVEL', 'TRAVEL')], max_length=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='shop_online.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('tag__in', ['OFFICE', 'PARTY', 'CASUAL', 'SPORT', 'DATE', 'WEDDING', 'TRAVEL'])), name='shop_online_ProductTag_tag_OccasionTag')],
                'unique_together': {('product', 'tag')},
            },
        ),
    ]
