# Generated by Django 6.0.7 on 2026-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0012_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
