# Generated by Django 6.0.7 on 2026-09-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0013_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop_online.orderitem'),
        ),
    ]
