# Generated by Django 6.0.7 on 2026-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0014_alter_review_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.URLField(),
        ),
    ]
