# Generated by Django 6.0.7 on 2026-09-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_online', '0015_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistylistsession',
            name='previous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='shop_online.aistylistsession'),
        ),
    ]
