"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import firebase_admin
from firebase_admin import credentials
import os
from celery.schedules import crontab
import platform
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FIREBASE_CRED_PATH = os.path.join(BASE_DIR, 'firebase_credential.json')
if not firebase_admin._apps:
    cred = credentials.Certificate(FIREBASE_CRED_PATH)
    firebase_admin.initialize_app(cred, {
        'databaseURL': 'https://shop-online-chat-default-rtdb.asia-southeast1.firebasedatabase.app/'
    })

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ae33#nkv84r%*x&4gz8i)w3i)^(ijzi0a_-*u2vz=smu%^^##j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.60','127.0.0.1', '192.168.1.3', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'drf_yasg',
    'rest_framework',
    'shop_online',
    'ckeditor',
    'ckeditor_uploader',
    'cloudinary',
    'cloudinary_storage',
    'oauth2_provider',
    'django_celery_beat',
    'corsheaders',

]

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUD_NAME'),
    'API_KEY': config('API_KEY'),
    'API_SECRET': config('API_SECRET'),
}
cloudinary.config(
    cloud_name=config('CLOUD_NAME'),
    api_key=config('API_KEY'),
    api_secret=config('API_SECRET'),
)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CKEDITOR_UPLOAD_PATH = "uploads/"

AUTH_USER_MODEL = "shop_online.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ),
}

OAUTH2_PROVIDER = {'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'}
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = "2351050148quy@ou.edu.vn"
SHOP_LATITUDE = config('SHOP_LATITUDE', cast=float)
SHOP_LONGITUDE = config('SHOP_LONGITUDE', cast=float)
PAYOS_CLIENT_ID = config('PAYOS_CLIENT_ID')
PAYOS_API_KEY = config('PAYOS_API_KEY')
PAYOS_CHECKSUM_KEY = config('PAYOS_CHECKSUM_KEY')
PAYOS_CANCEL_URL = config('PAYOS_CANCEL_URL')
PAYOS_RETURN_URL = config('PAYOS_RETURN_URL')
PAYOS_API_BASE = config('PAYOS_API_BASE')
PAYOS_PAYOUT_CLIENT_ID = config('PAYOS_PAYOUT_CLIENT_ID')
PAYOS_PAYOUT_API_KEY = config('PAYOS_PAYOUT_API_KEY')
PAYOS_PAYOUT_CHECKSUM_KEY = config('PAYOS_PAYOUT_CHECKSUM_KEY')
CELERY_BROKER_URL = config('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND =config('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'check-pending-refunds-every-1-minutes': {
        'task': 'shop_online.tasks.check_pending_refunds',
        'schedule': 60.0,
    },
    'check-low-stock-every-1-minutes': {
        'task': 'shop_online.tasks.check_low_stock',
        'schedule': 60.0,
    },
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shop_online.middleware.OAuthClientInfectionMiddleware'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

ROOT_URLCONF = 'apis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
if os.path.exists('/.dockerenv'):
    DB_HOST = 'host.docker.internal'
else:
    DB_HOST = 'localhost'
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',
        'NAME': 'testdb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': DB_HOST,
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


if platform.system() == "Windows":
    GDAL_LIBRARY_PATH = r"C:\Users\Admin\AppData\Local\Programs\OSGeo4W\bin\gdal313.dll"
    GEOS_LIBRARY_PATH = r"C:\Users\Admin\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
